# Generated by Django 3.0.1 on 2019-12-20 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191220_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='friday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=''), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='monday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=''), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='saturday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=''), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='sunday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=''), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='thursday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=''), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='tuesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=''), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='wednesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default=''), size=4), size=4),
        ),
    ]
