# Generated by Django 3.0.1 on 2020-01-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200101_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
