# Generated by Django 3.0.1 on 2020-01-01 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='friday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=5), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='days',
            name='saturday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=5), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='sunday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=5), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='thursday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=5), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='tuesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=5), size=4), size=4),
        ),
        migrations.AlterField(
            model_name='days',
            name='wednesday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=5), size=4), size=4),
        ),
    ]
