# Generated by Django 3.0.1 on 2020-01-01 19:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200101_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='monday',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=5), size=4), size=4),
        ),
    ]
